### ISSUE TITLE
CAH-0016: [BUG] Interaction with Stale Connection Crashes Server

### ISSUE THREAD

**Issue by TeamHaircut** [TeamHaircut/CAH#28]
**Describe the bug**
Server crashes if user turns off mobile screen, or changes internet tabs or apps and then tries to send msg across stale connection.

**To Reproduce**
1.  Connect a mobile user
2a. Use mobile power button to turn off device
2b. Open and use a different browser tab on mobile device
2c. Switch to a different app
2d. Allow device to automatically dim screen and turn off
3  Emit a message (send a message to group)

**Actual behavior**
Step 2 triggers socket disconnect.  Attempting to send a message from mobile device will crash server, and consequently break the connections of all users on server.

**Expected behavior**
Mobile user does not disconnect as a result of a step 2 event.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS
 - Browser safari
 - Version all

**Version/Commit**
CAH-0015 and later

**Additional context**
Refreshing browser on mobile device, reconnects user to room.  
.../CAH/CAH-Application/server.js:114
    io.to(user.room).emit('message', formatMessage(user.username, msg));
               ^

TypeError: Cannot read property 'room' of undefined
    at Socket.<anonymous> (.../CAH/CAH-Application/server.js:114:16)
    at Socket.emit (events.js:315:20)
    at .../CAH/CAH-Application/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by TeamHaircut** [comment]
fixed with pull request CAH-0016
