### ISSUE TITLE
CAH-0026: [BUG] Selecting disconnected user as winner breaks app server

### ISSUE THREAD

**Issue by TeamHaircut** [TeamHaircut/CAH#63]
**Describe the bug**
Selecting the whitecard of a disconnected user (one who leaves the room mid-round) as the winner will break the app server

**To Reproduce**
1. Reproduce CAH-0025
2. Select the card of the user that was disconnected
3. App server breaks

**Expected behavior**
Next round proceeds with one less user

**Tested on Desktop (please complete the following information):**
 - OS: [win 7]
 - Browser [chrome]
 - Version [latest]

**Version/Commit**
CAH-0024 and later

**Additional context**
CAH-0025 may or may not allow czar to select a winner.

if it does...CAH-0026 will generate the following error
CAH/CAH-Application-Mongo/utils/game.js:87
                var cardIndex = roomUserList[userIndex].whiteCards.findIndex(whiteCard => whiteCard === card.whiteCard);
                                                        ^

TypeError: Cannot read property 'whiteCards' of undefined
    at CAH/CAH-Application-Mongo/utils/game.js:87:43
    at Array.forEach (<anonymous>)
    at replaceWhiteCards (CAH/CAH-Application-Mongo/utils/game.js:85:11)
    at Socket.<anonymous> (CAH/CAH-Application-Mongo/server.js:187:29)
    at Socket.emit (events.js:315:20)
    at CAH/CAH-Application-Mongo/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by TeamHaircut** [comment]
fixed with CAH-0025
